# Generated by Django 5.0.7 on 2024-07-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='drop_time',
            field=models.DateTimeField(),
        ),
    ]
