# Generated by Django 5.0.7 on 2024-07-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_booking_drop_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pickup_time',
            field=models.DateTimeField(),
        ),
    ]
